# Workflow to build and publish the develop branch

name: Build on develop

on:
  # Will only be called from other workflows.
  workflow_call:
    inputs:
      do_pack:
        description: 'If this build should be packed as NuGet package.'
        required: true
        type: boolean

jobs:
  develop:
    # Run build-and-pack.yml
    uses: ./.github/workflows/build-and-pack.yml
    with:
      configuration: "Debug"
      do_pack: ${{ inputs.do_pack }}
      is_prerelease: true
      suffix: "beta"
      publish_target: "nuget.org"
    # Pass on secrets to the next workflow.
    secrets: inherit
