# Publish the build artifact (Nuget) to a target nuget feed.

name: Publish-Artifact

on:
  workflow_call:
    inputs:
      target:
        description: 'Define the target feed to push the artifact (e.g. nuget.org).'
        required: true
        type: string

jobs: 
  nuget-org-publish:
  
    if: inputs.target == 'nuget.org'
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download nugets from artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages
        path: package_output
    - name: Push to nuget.org
      # Publish all packages in "package_output". Skip if already published. Don't upload symbol packages. Get API key from secret "NUGET_FEED_PAT".
      run: dotnet nuget push package_output/*.nupkg --skip-duplicate --no-symbols --api-key ${{ secrets.NUGET_FEED_PAT }} --source https://api.nuget.org/v3/index.json
